development:

production:
  port: 80
  device_ttl: 3600
  redis:
    url: rediss://:<password>@<host>:<port>/<database>
  flakeid:
    datacenter: 0
    worker: 0
  io:
    pingTimeout: 60000
  winston:
    file:
      level: info
      filename: ./logs/log.txt
      handleExceptions: true
      json: true
      maxsize: 5242880 #5MB
      maxFiles: 5
      colorize: false
    console:
      level: info
