development:

production:
  port: 80
  device_ttl: 3600
  redis:
    port: 6379
    host: 127.0.0.1
    auth_pass: 12345
  flakeid:
    datacenter: 0
    worker: 0
  io:
    pingTimeout: 60000
  airbrake:
    key: 12345
    protocol: https
    serviceHost: api.airbrake.io
  winston:
    file:
      level: info
      filename: ./logs/log.txt
      handleExceptions: true
      json: true
      maxsize: 5242880 #5MB
      maxFiles: 5
      colorize: false
    console:
      level: info
  # servers to deploy to
  servers:
    - server1.example.net
    - server2.example.net
