development:

production:
  port: 80
  client_ttl: 3600
  redis:
    port: 6379
    host: 127.0.0.1
    auth_pass: 12345
  flakeid:
    datacenter: 0
    worker: 0
  io:
    pingTimeout: 60000
  airbrake:
    key: 12345
    protocol: https
    serviceHost: api.airbrake.io
